### ISSUE TITLE
Some compatibility issues

### ISSUE THREAD

**Issue by strooonger** [ooni/probe-android#146]
Hi,

I noticed that you have used `onReceivedError(WebView view, WebResourceRequest request, WebResourceError error)` in the class `BrowserActivity` to show a network error in webview window.

For your reference, `onReceivedError(WebView view, WebResourceRequest request, WebResourceError error)` is added in API version 23. For the devices with API version <=22, `onReceivedError(WebView view, WebResourceRequest request, WebResourceError error)` does not work because there is no such a method. (See this [link](https://stackoverflow.com/questions/32769505/webviewclient-onreceivederror-deprecated-new-version-does-not-detect-all-errors))

A possible fix is to add deprecated method `void onReceivedError (WebView view, int errorCode,String description,String failingUrl)` since this method supports all API versions.

Hope this information can help you. Thanks.

**Comment by bassosimone** [comment]
Thanks for contributing this useful list of thing we can do to improve the app! :-)

**Comment by hellais** [comment]
Hi @strooonger I believe this issue is related to the one mentioned inside of this paper: http://sccpu2.cse.ust.hk/andrewust/files/ASE18-Cider.pdf (maybe you are the author? If you are, good job and thanks for including OONI Probe in it!).

We are currently working on significantly reworking our mobile app and I suspect that some of these patterns will change in future versions.

Would it be possible to run your tool against the codebase of the revamped OONI Probe app to check if there are still similar callback related issues?

**Comment by xanscale** [comment]
made a quick fix waiting a complete rework 
https://github.com/ooni/probe-android/commit/4c87bbb6cb40c12ef2c2bae34443ce5f3b169065
